### ISSUE TITLE
Algorithm for another rule

### ISSUE THREAD

**Issue by dungcau1** [henrycharlesworth/big2_PPOalgorithm#6]
if the end game condition is change to end only if there are one player left. Could you give some ideas about the algorithm code to adapt to this

**Comment by henrycharlesworth** [comment]
Hi! Apologies for taking such a long time to reply, I only just saw this. It's been a while since I actually coded this up (and I haven't tested anything like this myself) - I would say the main thing you need to change is in the "big2Game.py" file - in the updateGame function you would need to change this condition:

if self.currentHands[self.playersGo].size == 0:
            self.assignRewards()
            self.gameOver = 1
            return

and also at the start of the function:

self.playersGo += 1
            if self.playersGo == 5:
                self.playersGo = 1
            self.passCount += 1
            if self.passCount == 3:
                self.control = 1
                self.passCount = 0
            return

would need to change. I didn't think about this at all when I was designing it though so it's likely that there would be other issues too, but ultimately it's just the game logic within big2Game.py that needs changing. Let me know how you get on!
